language: android
jdk: oraclejdk7

env:
    global:
        - ANDROID_BUILD_API_LEVEL=22
        - ANDROID_BUILD_TOOLS_VERSION=22.0.1
        - ANDROID_ABI=default/x86
        - ANDROID_EMULATOR_API_LEVEL=19

android:
    components:
        #- platform-tools
        #- tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_BUILD_API_LEVEL
        
        - extra-google-google_play_services
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository

notifications:
    email: true

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
    # for gradle output style
    - export TERM=dumb

    # environment info
    - ./gradlew -v
    - uname -a
    
    # AWS CLI Using pip
    - sudo pip install awscli
    
# build
script:
    - ./build_and_deploy.sh
