language: android
jdk: oraclejdk7

env:
    global:
        - ANDROID_BUILD_API_LEVEL=22
        - ANDROID_BUILD_TOOLS_VERSION=22.0.1
        - ANDROID_ABI=default/x86
        - ANDROID_EMULATOR_API_LEVEL=19

android:
    components:
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_BUILD_API_LEVEL
        
        - extra-google-google_play_services
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository

notifications:
    email: true

before_script:
    # for gradle output style
    - export TERM=dumb

    # environment info
    - ./gradlew -v
    - uname -a
    
    - sudo pip install awscli
    - sudo pip install pexpect
    - sudo pip install requests
    - sudo pip install requests[security]
    - sudo pip install boto3 
    
# build
script:
    - ./gradlew assembleDebug
    - ./gradlew assembleAndroidTest
    - python aws_pr_test.py
    
    
