language: android
jdk: oraclejdk7

env:
    global:
        - ANDROID_BUILD_API_LEVEL=22
        - ANDROID_BUILD_TOOLS_VERSION=22.0.1
        - ANDROID_ABI=default/x86
        - ANDROID_EMULATOR_API_LEVEL=19

android:
    components:
        #- platform-tools
        #- tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_BUILD_API_LEVEL
        #- android-$ANDROID_EMULATOR_API_LEVEL
        
        #- addon-google_apis_x86-google-$ANDROID_EMULATOR_API_LEVEL
        
        - extra-google-google_play_services
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository
        
        #- sys-img-x86-addon-google_apis-google-$ANDROID_EMULATOR_API_LEVEL

notifications:
    email: true

#before_install:
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
    # for gradle output style
    - export TERM=dumb

    # environment info
    - ./gradlew -v
    - uname -a
    
# build
script:
    #- ./gradlew clean connectedCheck -PdisablePreDex
    - ./gradlew clean assembleDebug